  name = "gifty"
  compatibility_date = "2024-01-01"
  pages_build_output_dir = ".output/public"

  [[d1_databases]]
  binding = "DB"
  database_name = "gifty-db"
  database_id = "preview-id-placeholder"
